const express = require('express')
const admin_route=express.Router();
const adminControllerLogin = require('../controller/adminController/adminLogin')
const adminControllerCategory = require('../controller/adminController/category')
const adminControllerUser = require('../controller/adminController/User')
const adminControllerCompany = require('../controller/adminController/company')
const adminControllerPremium = require('../controller/adminController/Premium')
const adminControllerProfile = require('../controller/adminController/profile')
const adminControllerTokenCheck  = require('../controller/adminController/tokenCheck')
const adminControllerDashBoard  = require('../controller/adminController/dashBoard')
const adminControllerJob = require('../controller/adminController/job')
const adminAuth  = require('../middleware/adminAuth')


admin_route.post('/login',adminControllerLogin.check)
admin_route.post('/createCategory',adminControllerCategory.createCategory)
admin_route.get('/categoryData',adminControllerCategory.categoryData)
admin_route.get('/categoryGet',adminControllerCategory.getCategory)
admin_route.post('/updateCategory',adminControllerCategory.updateCategory)
admin_route.delete('/deleteCategory',adminControllerCategory.deleteCategory)
admin_route.get('/userData',adminControllerUser.userData)
admin_route.get('/blockHandle',adminControllerUser.blockHandle)
admin_route.get('/companyData',adminControllerCompany.companyData)
admin_route.patch('/updateStatus',adminControllerCompany.approve)
admin_route.post('/createPlan',adminControllerPremium.createPremium)
admin_route.get('/premiumData',adminControllerPremium.premiumDataGet)
admin_route.get('/premiumDataById',adminControllerPremium.premiumDataGetById)
admin_route.delete('/deletePremium',adminControllerPremium.deletePremium)
admin_route.patch('/activePremium',adminControllerPremium.activePremium)
admin_route.put('/updatePremium',adminControllerPremium.updatePremium)
admin_route.get('/profileData',adminControllerProfile.getProfileData)
admin_route.put('/updateProfile',adminControllerProfile.updateProfile)
admin_route.get('/token_check',adminAuth,adminControllerTokenCheck.tokenCheck)
admin_route.get('/job_data',adminControllerJob.jobData)
admin_route.get('/fetchDatas',adminAuth,adminControllerDashBoard.fetchDatas)
module.exports=admin_route;